// Design System — Tokens used by this component
// Auto-generated by scripts/export-tokens.js — do not edit by hand.
// Assumes UIColor(hex:) initializer exists in your project.

import UIKit

// MARK: - Colors

extension UIColor {
    static let brandPrimary100 = UIColor(hex: "#C7E5FA")
    static let brandPrimary200 = UIColor(hex: "#8AC8F5")
    static let brandPrimary500 = UIColor(hex: "#1383D4")
    static let textSecondary = UIColor(hex: "#657078")
    static let textDisabled = UIColor(hex: "#A7ADB2")
}

// MARK: - Spacing

extension CGFloat {
    static let space3: CGFloat = 12
    static let space6: CGFloat = 24
    static let space1: CGFloat = 4
    static let space2: CGFloat = 8
    static let space12: CGFloat = 48
    static let space4: CGFloat = 16
    static let space8: CGFloat = 32
    static let space5: CGFloat = 20
}
