// Design System — Tokens used by this component
// Auto-generated by scripts/export-tokens.js — do not edit by hand.
// Assumes UIColor(hex:) initializer exists in your project.

import UIKit

// MARK: - Colors

extension UIColor {
    static let brandPrimary500 = UIColor(hex: "#1383D4")
    static let neutralGrey300 = UIColor(hex: "#DFE2E2")
    static let neutralGrey400 = UIColor(hex: "#C9CFCF")
    static let neutralGrey600 = UIColor(hex: "#667070")
    static let neutralGrey800 = UIColor(hex: "#1F2323")
    static let neutralGrey900 = UIColor(hex: "#131515")
    static let textPrimary = UIColor(hex: "#121F28")
    static let textDisabled = UIColor(hex: "#A7ADB2")
    static let btnPrimary600 = UIColor(hex: "#0F69AA")
    static let btnPrimary700 = UIColor(hex: "#024A72")
}

// MARK: - Spacing

extension CGFloat {
    static let space4: CGFloat = 16
    static let space2: CGFloat = 8
    static let space8: CGFloat = 32
    static let space16: CGFloat = 64
    static let space6: CGFloat = 24
}
