// Design System — Tokens used by this component
// Auto-generated by scripts/export-tokens.js — do not edit by hand.
// Assumes UIColor(hex:) initializer exists in your project.

import UIKit

// MARK: - Colors

extension UIColor {
    static let brandPrimary500 = UIColor(hex: "#1383D4")
    static let brandPrimary600 = UIColor(hex: "#0F69A9")
    static let scaleRed600 = UIColor(hex: "#8E2A1F")
    static let neutralGrey900 = UIColor(hex: "#131515")
    static let surfaceRow = UIColor(hex: "#FFFFFF")
    static let surfaceTableHeader = UIColor(hex: "#F7F8F8")
    static let textPrimary = UIColor(hex: "#121F28")
    static let textSecondary = UIColor(hex: "#657078")
    static let textDisabled = UIColor(hex: "#A7ADB2")
    static let textPlaceholder = UIColor(hex: "#A7ADB2")
    static let textInverse = UIColor(hex: "#FFFFFF")
    static let textOnAccent = UIColor(hex: "#FFFFFF")
    static let textLink = UIColor(hex: "#0066CC")
    static let textSuccess = UIColor(hex: "#2F7D2C")
    static let textWarning = UIColor(hex: "#8E6800")
    static let textError = UIColor(hex: "#B0291E")
}

// MARK: - Sizing (CGFloat)

extension CGFloat {
    // Spacing
    static let space2: CGFloat = 8
    static let space4: CGFloat = 16
    static let space3: CGFloat = 12
    static let space8: CGFloat = 32
    static let space10: CGFloat = 40
    static let space6: CGFloat = 24
    static let space5: CGFloat = 20
    static let space1: CGFloat = 4
    static let space12: CGFloat = 48

    // Radius
    static let radiusMd: CGFloat = 6
    static let radiusXl: CGFloat = 12

    // Border width
    static let borderWidth1: CGFloat = 1

    // Font size
    static let fontSize10: CGFloat = 10
    static let fontSize11: CGFloat = 11
    static let fontSize12: CGFloat = 12
    static let fontSize13: CGFloat = 13
    static let fontSize14: CGFloat = 14
    static let fontSize15: CGFloat = 15
    static let fontSize16: CGFloat = 16
    static let fontSize24: CGFloat = 24
    static let fontSize28: CGFloat = 28
    static let fontSize36: CGFloat = 36
    static let fontSize56: CGFloat = 56
    static let fontSize72: CGFloat = 72

    // Focus ring width
    static let ringWidth1: CGFloat = 1
}

// MARK: - Font weights (use UIFont.Weight directly)
// font-weight-medium → .medium   (CSS 500)
// font-weight-semibold → .semibold   (CSS 600)
// font-weight-normal → .regular   (CSS 400)
// font-weight-bold → .bold   (CSS 700)
