// Design System — Tokens used by this component
// Auto-generated by scripts/export-tokens.js — do not edit by hand.
// Assumes UIColor(hex:) initializer exists in your project.

import UIKit

// MARK: - Colors

extension UIColor {
    static let brandPrimary500 = UIColor(hex: "#1383D4")
    static let neutralGrey100 = UIColor(hex: "#F7F8F8")
    static let neutralGrey200 = UIColor(hex: "#F4F5F5")
    static let surfaceTableHeader = UIColor(hex: "#F7F8F8")
    static let textPrimary = UIColor(hex: "#121F28")
    static let textSecondary = UIColor(hex: "#657078")
    static let textDisabled = UIColor(hex: "#A7ADB2")
}

// MARK: - Sizing (CGFloat)

extension CGFloat {
    // Spacing
    static let space2: CGFloat = 8
    static let space4: CGFloat = 16
    static let space16: CGFloat = 64
    static let space6: CGFloat = 24
    static let space5: CGFloat = 20
    static let space3: CGFloat = 12
    static let space1: CGFloat = 4
    static let space12: CGFloat = 48
    static let space8: CGFloat = 32
    static let space10: CGFloat = 40

    // Radius
    static let radiusSm: CGFloat = 2
    static let radiusMd: CGFloat = 6
    static let radiusLg: CGFloat = 8
    static let radiusXl: CGFloat = 12
    static let radius2xl: CGFloat = 16
    static let radiusFull: CGFloat = 9999

    // Border width
    static let borderWidth1: CGFloat = 1

    // Font size
    static let fontSize10: CGFloat = 10
    static let fontSize11: CGFloat = 11
    static let fontSize12: CGFloat = 12
    static let fontSize14: CGFloat = 14
    static let fontSize15: CGFloat = 15
}

// MARK: - Font weights (use UIFont.Weight directly)
// font-weight-medium → .medium   (CSS 500)
// font-weight-semibold → .semibold   (CSS 600)

// MARK: - Z-Index Layers

extension Int {
    static let zBase: Int = 0
    static let zSticky: Int = 10
    static let zDropdown: Int = 20
    static let zOverlay: Int = 30
    static let zSidebar: Int = 40
    static let zModal: Int = 50
    static let zToast: Int = 60
}

// MARK: - Motion Durations (TimeInterval, seconds)

extension TimeInterval {
    static let motionDurationInstant: TimeInterval = 0.075
    static let motionDurationSnap: TimeInterval = 0.1
    static let motionDurationDefault: TimeInterval = 0.15
    static let motionDurationEmphasis: TimeInterval = 0.2
    static let motionDurationSpatial: TimeInterval = 0.3
}
