// Design System — Tokens used by this component
// Auto-generated by scripts/export-tokens.js — do not edit by hand.
// Assumes UIColor(hex:) initializer exists in your project.

import UIKit

// MARK: - Colors

extension UIColor {
    static let brandPrimary500 = UIColor(hex: "#1383D4")
    static let surfaceApp = UIColor(hex: "#FFFFFF")
    static let surfacePage = UIColor(hex: "#FCFDFD")
    static let surfaceTableHeader = UIColor(hex: "#F7F8F8")
    static let textPrimary = UIColor(hex: "#121F28")
    static let textSecondary = UIColor(hex: "#657078")
    static let textDisabled = UIColor(hex: "#A7ADB2")
}

// MARK: - Sizing (CGFloat)

extension CGFloat {
    // Spacing
    static let space8: CGFloat = 32
    static let space6: CGFloat = 24
    static let space4: CGFloat = 16
    static let space10: CGFloat = 40
    static let space3: CGFloat = 12
    static let space12: CGFloat = 48
    static let space16: CGFloat = 64

    // Radius
    static let radiusXl: CGFloat = 12

    // Border width
    static let borderWidth1: CGFloat = 1

    // Font size
    static let fontSize10: CGFloat = 10
    static let fontSize11: CGFloat = 11
    static let fontSize12: CGFloat = 12
    static let fontSize13: CGFloat = 13
}

// MARK: - Font weights (use UIFont.Weight directly)
// font-weight-medium → .medium   (CSS 500)
// font-weight-semibold → .semibold   (CSS 600)
