// Design System — Tokens used by this component
// Auto-generated by scripts/export-tokens.js — do not edit by hand.
// Assumes UIColor(hex:) initializer exists in your project.

import UIKit

// MARK: - Colors

extension UIColor {
    static let brandPrimary500 = UIColor(hex: "#1383D4")
    static let brandPrimary600 = UIColor(hex: "#0F69A9")
    static let scaleGreen600 = UIColor(hex: "#3F6600")
    static let neutralGrey100 = UIColor(hex: "#F7F8F8")
    static let neutralGrey200 = UIColor(hex: "#F4F5F5")
    static let surfaceApp = UIColor(hex: "#FFFFFF")
    static let data1 = UIColor(hex: "#9ACBE5")
    static let data2 = UIColor(hex: "#FFAF97")
    static let data3 = UIColor(hex: "#C4DEF3")
    static let data5 = UIColor(hex: "#0F69AA")
    static let data7 = UIColor(hex: "#1F5077")
    static let textPrimary = UIColor(hex: "#121F28")
    static let textSecondary = UIColor(hex: "#657078")
    static let textDisabled = UIColor(hex: "#A7ADB2")
    static let textOnAccent = UIColor(hex: "#FFFFFF")
}

// MARK: - Spacing

extension CGFloat {
    static let space3: CGFloat = 12
    static let space4: CGFloat = 16
    static let space5: CGFloat = 20
    static let space1: CGFloat = 4
    static let space2: CGFloat = 8
    static let space8: CGFloat = 32
    static let space6: CGFloat = 24
}
