// Design System — Tokens used by this component
// Auto-generated by scripts/export-tokens.js — do not edit by hand.
// Assumes UIColor(hex:) initializer exists in your project.

import UIKit

// MARK: - Colors

extension UIColor {
    static let brandPrimary500 = UIColor(hex: "#1383D4")
    static let brandPrimary600 = UIColor(hex: "#0F69A9")
    static let scaleGreen600 = UIColor(hex: "#3F6600")
    static let neutralGrey100 = UIColor(hex: "#F7F8F8")
    static let neutralGrey200 = UIColor(hex: "#F4F5F5")
    static let surfaceApp = UIColor(hex: "#FFFFFF")
    static let data1 = UIColor(hex: "#9ACBE5")
    static let data2 = UIColor(hex: "#FFAF97")
    static let data3 = UIColor(hex: "#C4DEF3")
    static let data5 = UIColor(hex: "#0F69AA")
    static let data7 = UIColor(hex: "#1F5077")
    static let textPrimary = UIColor(hex: "#121F28")
    static let textSecondary = UIColor(hex: "#657078")
    static let textDisabled = UIColor(hex: "#A7ADB2")
    static let textOnAccent = UIColor(hex: "#FFFFFF")
}

// MARK: - Sizing (CGFloat)

extension CGFloat {
    // Spacing
    static let space3: CGFloat = 12
    static let space4: CGFloat = 16
    static let space5: CGFloat = 20
    static let space1: CGFloat = 4
    static let space2: CGFloat = 8
    static let space10: CGFloat = 40
    static let space8: CGFloat = 32
    static let space6: CGFloat = 24
    static let space11: CGFloat = 44
    static let space12: CGFloat = 48
    static let space16: CGFloat = 64

    // Radius
    static let radiusBase: CGFloat = 4
    static let radiusMd: CGFloat = 6
    static let radiusLg: CGFloat = 8
    static let radiusXl: CGFloat = 12
    static let radiusFull: CGFloat = 9999

    // Border width
    static let borderWidth1: CGFloat = 1

    // Font size
    static let fontSize10: CGFloat = 10
    static let fontSize11: CGFloat = 11
    static let fontSize12: CGFloat = 12
    static let fontSize13: CGFloat = 13
    static let fontSize14: CGFloat = 14
    static let fontSize15: CGFloat = 15
    static let fontSize16: CGFloat = 16
}

// MARK: - Font weights (use UIFont.Weight directly)
// font-weight-medium → .medium   (CSS 500)
// font-weight-semibold → .semibold   (CSS 600)
// font-weight-bold → .bold   (CSS 700)
