// Design System — Tokens used by this component
// Auto-generated by scripts/export-tokens.js — do not edit by hand.
// Assumes UIColor(hex:) initializer exists in your project.

import UIKit

// MARK: - Colors

extension UIColor {
    static let brandPrimary500 = UIColor(hex: "#1383D4")
    static let brandPrimary600 = UIColor(hex: "#0F69A9")
    static let brandPrimary700 = UIColor(hex: "#09436C")
    static let neutralGrey100 = UIColor(hex: "#F7F8F8")
    static let neutralGrey900 = UIColor(hex: "#131515")
    static let surfaceApp = UIColor(hex: "#FFFFFF")
    static let feedbackInfo = UIColor(hex: "#7DAFD6")
    static let feedbackSuccess = UIColor(hex: "#63A100")
    static let feedbackWarning = UIColor(hex: "#E6A200")
    static let feedbackAlert = UIColor(hex: "#AE2700")
    static let textPrimary = UIColor(hex: "#121F28")
    static let textSecondary = UIColor(hex: "#657078")
    static let textDisabled = UIColor(hex: "#A7ADB2")
    static let textInverse = UIColor(hex: "#FFFFFF")
}

// MARK: - Sizing (CGFloat)

extension CGFloat {
    // Spacing
    static let space2: CGFloat = 8
    static let space3: CGFloat = 12
    static let space4: CGFloat = 16
    static let space10: CGFloat = 40
    static let space6: CGFloat = 24
    static let space8: CGFloat = 32
    static let space5: CGFloat = 20
    static let space1: CGFloat = 4

    // Radius
    static let radiusLg: CGFloat = 8
    static let radiusXl: CGFloat = 12

    // Border width
    static let borderWidth1: CGFloat = 1
    static let borderWidth4: CGFloat = 4

    // Font size
    static let fontSize10: CGFloat = 10
    static let fontSize12: CGFloat = 12
    static let fontSize13: CGFloat = 13
    static let fontSize15: CGFloat = 15
}

// MARK: - Font weights (use UIFont.Weight directly)
// font-weight-medium → .medium   (CSS 500)
// font-weight-semibold → .semibold   (CSS 600)
