// Design System — Tokens used by this component
// Auto-generated by scripts/export-tokens.js — do not edit by hand.
// Assumes UIColor(hex:) initializer exists in your project.

import UIKit

// MARK: - Colors

extension UIColor {
    static let severityInfo = UIColor(hex: "#7DAFD6")
    static let severityLow = UIColor(hex: "#63A100")
    static let severityMedium = UIColor(hex: "#F5BF40")
    static let severityHigh = UIColor(hex: "#D13D2E")
    static let severityCritical = UIColor(hex: "#772ED1")
    static let brandPrimary50 = UIColor(hex: "#E8F4FD")
    static let brandPrimary500 = UIColor(hex: "#1383D4")
    static let brandPrimary600 = UIColor(hex: "#0F69A9")
    static let brandSecondary500 = UIColor(hex: "#EE7B59")
    static let scaleBlue50 = UIColor(hex: "#F7FAFD")
    static let scaleBlue200 = UIColor(hex: "#C9DEEE")
    static let scaleBlue500 = UIColor(hex: "#7DAFD6")
    static let scaleBlue600 = UIColor(hex: "#2F6893")
    static let scaleGreen50 = UIColor(hex: "#F1FFDB")
    static let scaleGreen500 = UIColor(hex: "#63A100")
    static let scaleGreen600 = UIColor(hex: "#3F6600")
    static let scaleYellow50 = UIColor(hex: "#FEFAF0")
    static let scaleYellow500 = UIColor(hex: "#F5BF40")
    static let scaleYellow700 = UIColor(hex: "#795706")
    static let scaleRed50 = UIColor(hex: "#FCF3F2")
    static let scaleRed200 = UIColor(hex: "#EBAAA3")
    static let scaleRed500 = UIColor(hex: "#D13D2E")
    static let scaleRed600 = UIColor(hex: "#8E2A1F")
    static let scalePurple50 = UIColor(hex: "#F7F2FC")
    static let scalePurple500 = UIColor(hex: "#772ED1")
    static let scalePurple600 = UIColor(hex: "#5D24A3")
    static let neutralGrey00 = UIColor(hex: "#FFFFFF")
    static let neutralGrey100 = UIColor(hex: "#F7F8F8")
    static let neutralGrey200 = UIColor(hex: "#F4F5F5")
    static let neutralGrey300 = UIColor(hex: "#DFE2E2")
    static let neutralGrey400 = UIColor(hex: "#C9CFCF")
    static let neutralGrey900 = UIColor(hex: "#131515")
    static let surfaceApp = UIColor(hex: "#FFFFFF")
    static let surfacePage = UIColor(hex: "#FCFDFD")
    static let surfaceRow = UIColor(hex: "#FFFFFF")
    static let surfaceTableHeader = UIColor(hex: "#F7F8F8")
    static let data1 = UIColor(hex: "#9ACBE5")
    static let data2 = UIColor(hex: "#FFAF97")
    static let data3 = UIColor(hex: "#C4DEF3")
    static let data4 = UIColor(hex: "#A7ADB2")
    static let data5 = UIColor(hex: "#0F69AA")
    static let data6 = UIColor(hex: "#C1674D")
    static let data7 = UIColor(hex: "#1F5077")
    static let data8 = UIColor(hex: "#394751")
    static let textPrimary = UIColor(hex: "#121F28")
    static let textSecondary = UIColor(hex: "#657078")
    static let textDisabled = UIColor(hex: "#A7ADB2")
    static let textWhite = UIColor(hex: "#FFFFFF")
    static let textOnAccent = UIColor(hex: "#FFFFFF")
    static let btnNeutral800 = UIColor(hex: "#202323")
    static let btnPrimary600 = UIColor(hex: "#0F69AA")
    static let btnPrimary700 = UIColor(hex: "#024A72")
}

// MARK: - Sizing (CGFloat)

extension CGFloat {
    // Spacing
    static let space2: CGFloat = 8
    static let space4: CGFloat = 16
    static let space1: CGFloat = 4
    static let space3: CGFloat = 12
    static let space9: CGFloat = 36
    static let space5: CGFloat = 20
    static let space8: CGFloat = 32
    static let space12: CGFloat = 48
    static let space10: CGFloat = 40
    static let space6: CGFloat = 24
    static let space16: CGFloat = 64

    // Radius
    static let radiusBase: CGFloat = 4
    static let radiusMd: CGFloat = 6
    static let radiusLg: CGFloat = 8
    static let radiusFull: CGFloat = 9999
    static let radiusXl: CGFloat = 12

    // Border width
    static let borderWidth1: CGFloat = 1

    // Font size
    static let fontSize9: CGFloat = 9
    static let fontSize10: CGFloat = 10
    static let fontSize11: CGFloat = 11
    static let fontSize12: CGFloat = 12
    static let fontSize13: CGFloat = 13
    static let fontSize14: CGFloat = 14
    static let fontSize15: CGFloat = 15
    static let fontSize16: CGFloat = 16
    static let fontSize20: CGFloat = 20
    static let fontSize22: CGFloat = 22
    static let fontSize26: CGFloat = 26

    // Focus ring width
    static let ringWidth1: CGFloat = 1
    static let ringWidth2: CGFloat = 2
}

// MARK: - Font weights (use UIFont.Weight directly)
// font-weight-medium → .medium   (CSS 500)
// font-weight-semibold → .semibold   (CSS 600)
// font-weight-bold → .bold   (CSS 700)
