// Design System — Tokens used by this component
// Auto-generated by scripts/export-tokens.js — do not edit by hand.
// Assumes UIColor(hex:) initializer exists in your project.

import UIKit

// MARK: - Colors

extension UIColor {
    static let brandPrimary500 = UIColor(hex: "#1383D4")
    static let textPrimary = UIColor(hex: "#121F28")
    static let textDisabled = UIColor(hex: "#A7ADB2")
    static let btnNeutral100 = UIColor(hex: "#F7F8F8")
    static let btnNeutral300 = UIColor(hex: "#DFE2E2")
    static let btnNeutral600 = UIColor(hex: "#667070")
    static let btnNeutral700 = UIColor(hex: "#444B4B")
    static let btnNeutral800 = UIColor(hex: "#202323")
    static let btnPrimary50 = UIColor(hex: "#EBF2F7")
    static let btnPrimary600 = UIColor(hex: "#0F69AA")
    static let btnPrimary700 = UIColor(hex: "#024A72")
    static let btnSuccess50 = UIColor(hex: "#EFF7E5")
    static let btnSuccess600 = UIColor(hex: "#406800")
    static let btnSuccess700 = UIColor(hex: "#284000")
    static let btnWarning50 = UIColor(hex: "#FFFBF0")
    static let btnWarning600 = UIColor(hex: "#E6A200")
    static let btnWarning700 = UIColor(hex: "#805A00")
    static let btnError50 = UIColor(hex: "#FFF0EF")
    static let btnError600 = UIColor(hex: "#AE2700")
    static let btnError700 = UIColor(hex: "#881F00")
}

// MARK: - Spacing

extension CGFloat {
    static let space3: CGFloat = 12
    static let space4: CGFloat = 16
    static let space2: CGFloat = 8
    static let space1: CGFloat = 4
    static let space8: CGFloat = 32
    static let space16: CGFloat = 64
    static let space6: CGFloat = 24
    static let space5: CGFloat = 20
    static let space12: CGFloat = 48
}
