// Design System — Tokens used by this component
// Auto-generated by scripts/export-tokens.js — do not edit by hand.
// Assumes UIColor(hex:) initializer exists in your project.

import UIKit

// MARK: - Colors

extension UIColor {
    static let brandPrimary500 = UIColor(hex: "#1383D4")
    static let neutralGrey100 = UIColor(hex: "#F7F8F8")
    static let neutralGrey300 = UIColor(hex: "#DFE2E2")
    static let neutralGrey800 = UIColor(hex: "#1F2323")
    static let textPrimary = UIColor(hex: "#121F28")
    static let textSecondary = UIColor(hex: "#657078")
    static let textDisabled = UIColor(hex: "#A7ADB2")
    static let textWhite = UIColor(hex: "#FFFFFF")
    static let textOnAccent = UIColor(hex: "#FFFFFF")
    static let btnPrimary600 = UIColor(hex: "#0F69AA")
}

// MARK: - Sizing (CGFloat)

extension CGFloat {
    // Spacing
    static let space3: CGFloat = 12
    static let space4: CGFloat = 16
    static let space6: CGFloat = 24
    static let space9: CGFloat = 36
    static let space2: CGFloat = 8
    static let space8: CGFloat = 32
    static let space16: CGFloat = 64
    static let space10: CGFloat = 40
    static let space5: CGFloat = 20

    // Radius
    static let radiusMd: CGFloat = 6
    static let radiusXl: CGFloat = 12
    static let radiusFull: CGFloat = 9999

    // Border width
    static let borderWidth1: CGFloat = 1
    static let borderWidth2: CGFloat = 2

    // Font size
    static let fontSize10: CGFloat = 10
    static let fontSize12: CGFloat = 12
    static let fontSize14: CGFloat = 14
    static let fontSize15: CGFloat = 15
}

// MARK: - Font weights (use UIFont.Weight directly)
// font-weight-medium → .medium   (CSS 500)
// font-weight-semibold → .semibold   (CSS 600)
