// Design System — Tokens used by this component
// Auto-generated by scripts/export-tokens.js — do not edit by hand.
// Assumes UIColor(hex:) initializer exists in your project.

import UIKit

// MARK: - Colors

extension UIColor {
    static let brandPrimary500 = UIColor(hex: "#1383D4")
    static let neutralGrey100 = UIColor(hex: "#F7F8F8")
    static let textPrimary = UIColor(hex: "#121F28")
    static let textSecondary = UIColor(hex: "#657078")
    static let textDisabled = UIColor(hex: "#A7ADB2")
    static let textWhite = UIColor(hex: "#FFFFFF")
    static let textOnAccent = UIColor(hex: "#FFFFFF")
    static let btnPrimary600 = UIColor(hex: "#0F69AA")
}

// MARK: - Spacing

extension CGFloat {
    static let space3: CGFloat = 12
    static let space4: CGFloat = 16
    static let space6: CGFloat = 24
    static let space2: CGFloat = 8
    static let space8: CGFloat = 32
    static let space16: CGFloat = 64
    static let space5: CGFloat = 20
}
