// Design System — Tokens used by this component
// Auto-generated by scripts/export-tokens.js — do not edit by hand.
// Assumes UIColor(hex:) initializer exists in your project.

import UIKit

// MARK: - Colors

extension UIColor {
    static let severityInfo = UIColor(hex: "#7DAFD6")
    static let severityLow = UIColor(hex: "#63A100")
    static let severityMedium = UIColor(hex: "#F5BF40")
    static let severityHigh = UIColor(hex: "#D13D2E")
    static let severityCritical = UIColor(hex: "#772ED1")
    static let brandPrimary500 = UIColor(hex: "#1383D4")
    static let scaleBlue600 = UIColor(hex: "#2F6893")
    static let scaleGreen600 = UIColor(hex: "#3F6600")
    static let scaleYellow700 = UIColor(hex: "#795706")
    static let scaleRed600 = UIColor(hex: "#8E2A1F")
    static let scalePurple600 = UIColor(hex: "#5D24A3")
    static let surfaceRow = UIColor(hex: "#FFFFFF")
    static let surfaceRowHover = UIColor(hex: "#EBF2F7")
    static let surfaceTableHeader = UIColor(hex: "#F7F8F8")
    static let textPrimary = UIColor(hex: "#121F28")
    static let textSecondary = UIColor(hex: "#657078")
    static let textDisabled = UIColor(hex: "#A7ADB2")
}

// MARK: - Spacing

extension CGFloat {
    static let space2: CGFloat = 8
    static let space4: CGFloat = 16
    static let space6: CGFloat = 24
    static let space5: CGFloat = 20
    static let space3: CGFloat = 12
    static let space8: CGFloat = 32
}
