// Design System — Tokens used by this component
// Auto-generated by scripts/export-tokens.js — do not edit by hand.
// Assumes UIColor(hex:) initializer exists in your project.

import UIKit

// MARK: - Colors

extension UIColor {
    static let brandPrimary500 = UIColor(hex: "#1383D4")
    static let scaleBlue50 = UIColor(hex: "#F7FAFD")
    static let scaleBlue200 = UIColor(hex: "#C9DEEE")
    static let scaleGreen50 = UIColor(hex: "#F1FFDB")
    static let scaleGreen200 = UIColor(hex: "#A5FF14")
    static let scaleYellow50 = UIColor(hex: "#FEFAF0")
    static let scaleYellow200 = UIColor(hex: "#F8D072")
    static let scaleYellow700 = UIColor(hex: "#795706")
    static let scaleRed50 = UIColor(hex: "#FCF3F2")
    static let scaleRed200 = UIColor(hex: "#EBAAA3")
    static let textPrimary = UIColor(hex: "#121F28")
    static let textSuccess = UIColor(hex: "#2F7D2C")
    static let textWarning = UIColor(hex: "#8E6800")
    static let textError = UIColor(hex: "#B0291E")
}

// MARK: - Spacing

extension CGFloat {
    static let space3: CGFloat = 12
    static let space4: CGFloat = 16
    static let space1: CGFloat = 4
    static let space2: CGFloat = 8
    static let space6: CGFloat = 24
    static let space5: CGFloat = 20
    static let space8: CGFloat = 32
}
