// Design System — Tokens used by this component
// Auto-generated by scripts/export-tokens.js — do not edit by hand.
// Assumes UIColor(hex:) initializer exists in your project.

import UIKit

// MARK: - Colors

extension UIColor {
    static let severityCritical = UIColor(hex: "#772ED1")
    static let brandPrimary50 = UIColor(hex: "#E8F4FD")
    static let brandPrimary500 = UIColor(hex: "#1383D4")
    static let brandPrimary600 = UIColor(hex: "#0F69A9")
    static let brandPrimary700 = UIColor(hex: "#09436C")
    static let brandPrimary800 = UIColor(hex: "#062C46")
    static let scaleGreen500 = UIColor(hex: "#63A100")
    static let scaleGreen600 = UIColor(hex: "#3F6600")
    static let scaleRed600 = UIColor(hex: "#8E2A1F")
    static let neutralGrey100 = UIColor(hex: "#F7F8F8")
    static let neutralGrey300 = UIColor(hex: "#DFE2E2")
    static let neutralGrey500 = UIColor(hex: "#949E9E")
    static let surfaceApp = UIColor(hex: "#FFFFFF")
    static let surfaceTableHeader = UIColor(hex: "#F7F8F8")
    static let textPrimary = UIColor(hex: "#121F28")
    static let textSecondary = UIColor(hex: "#657078")
    static let textDisabled = UIColor(hex: "#A7ADB2")
    static let textInverse = UIColor(hex: "#FFFFFF")
    static let textOnAccent = UIColor(hex: "#FFFFFF")
    static let textLink = UIColor(hex: "#0066CC")
    static let btnPrimary600 = UIColor(hex: "#0F69AA")
    static let btnPrimary700 = UIColor(hex: "#024A72")
    static let btnWarning600 = UIColor(hex: "#E6A200")
}

// MARK: - Sizing (CGFloat)

extension CGFloat {
    // Spacing
    static let space2: CGFloat = 8
    static let space4: CGFloat = 16
    static let space1: CGFloat = 4
    static let space3: CGFloat = 12
    static let space5: CGFloat = 20
    static let space9: CGFloat = 36
    static let space10: CGFloat = 40

    // Radius
    static let radiusBase: CGFloat = 4
    static let radiusMd: CGFloat = 6
    static let radiusXl: CGFloat = 12
    static let radiusFull: CGFloat = 9999

    // Border width
    static let borderWidth1: CGFloat = 1

    // Font size
    static let fontSize10: CGFloat = 10
    static let fontSize11: CGFloat = 11
    static let fontSize12: CGFloat = 12
    static let fontSize14: CGFloat = 14
    static let fontSize15: CGFloat = 15
}

// MARK: - Font weights (use UIFont.Weight directly)
// font-weight-medium → .medium   (CSS 500)
// font-weight-semibold → .semibold   (CSS 600)
