// Design System — Tokens used by this component
// Auto-generated by scripts/export-tokens.js — do not edit by hand.
// Assumes UIColor(hex:) initializer exists in your project.

import UIKit

// MARK: - Colors

extension UIColor {
    static let brandPrimary500 = UIColor(hex: "#1383D4")
    static let brandPrimary600 = UIColor(hex: "#0F69A9")
    static let scaleYellow50 = UIColor(hex: "#FEFAF0")
    static let scaleYellow600 = UIColor(hex: "#DA9C0B")
    static let scaleRed50 = UIColor(hex: "#FCF3F2")
    static let scaleRed600 = UIColor(hex: "#8E2A1F")
    static let neutralGrey100 = UIColor(hex: "#F7F8F8")
    static let surfaceApp = UIColor(hex: "#FFFFFF")
    static let textPrimary = UIColor(hex: "#121F28")
    static let textSecondary = UIColor(hex: "#657078")
    static let textWhite = UIColor(hex: "#FFFFFF")
}

// MARK: - Spacing

extension CGFloat {
    static let space6: CGFloat = 24
    static let space8: CGFloat = 32
    static let space12: CGFloat = 48
    static let space4: CGFloat = 16
    static let space5: CGFloat = 20
    static let space2: CGFloat = 8
}
