// Design System — Tokens for iOS
// Auto-generated by scripts/export-tokens.js — do not edit by hand.
//
// Usage:
//   view.backgroundColor = .severityCritical
//   constraint.constant  = .space4
//
// UIColor(hex:) is assumed to exist in your project. If not, add it once:
//   extension UIColor {
//     convenience init(hex: String) {
//       let v = UInt64(hex.dropFirst(), radix: 16) ?? 0
//       self.init(red:   CGFloat((v >> 16) & 0xff) / 255,
//                 green: CGFloat((v >>  8) & 0xff) / 255,
//                 blue:  CGFloat( v        & 0xff) / 255,
//                 alpha: 1)
//     }
//   }

import UIKit

// MARK: - Colors

extension UIColor {
    static let severityInfo = UIColor(hex: "#7DAFD6")
    static let severityLow = UIColor(hex: "#63A100")
    static let severityMedium = UIColor(hex: "#F5BF40")
    static let severityHigh = UIColor(hex: "#D13D2E")
    static let severityCritical = UIColor(hex: "#772ED1")
    static let brandPrimary50 = UIColor(hex: "#E8F4FD")
    static let brandPrimary100 = UIColor(hex: "#C7E5FA")
    static let brandPrimary200 = UIColor(hex: "#8AC8F5")
    static let brandPrimary500 = UIColor(hex: "#1383D4")
    static let brandPrimary600 = UIColor(hex: "#0F69A9")
    static let brandPrimary700 = UIColor(hex: "#09436C")
    static let brandPrimary800 = UIColor(hex: "#062C46")
    static let brandSecondary50 = UIColor(hex: "#FEF4F1")
    static let brandSecondary100 = UIColor(hex: "#FADAD1")
    static let brandSecondary200 = UIColor(hex: "#F5B6A3")
    static let brandSecondary500 = UIColor(hex: "#EE7B59")
    static let brandSecondary600 = UIColor(hex: "#E85326")
    static let brandSecondary700 = UIColor(hex: "#C23D14")
    static let brandSecondary800 = UIColor(hex: "#81290E")
    static let scaleBlue50 = UIColor(hex: "#F7FAFD")
    static let scaleBlue100 = UIColor(hex: "#E8F1F8")
    static let scaleBlue200 = UIColor(hex: "#C9DEEE")
    static let scaleBlue500 = UIColor(hex: "#7DAFD6")
    static let scaleBlue600 = UIColor(hex: "#2F6893")
    static let scaleBlue700 = UIColor(hex: "#234F70")
    static let scaleBlue800 = UIColor(hex: "#18374E")
    static let scaleGreen50 = UIColor(hex: "#F1FFDB")
    static let scaleGreen100 = UIColor(hex: "#E8FFC2")
    static let scaleGreen200 = UIColor(hex: "#A5FF14")
    static let scaleGreen500 = UIColor(hex: "#63A100")
    static let scaleGreen600 = UIColor(hex: "#3F6600")
    static let scaleGreen700 = UIColor(hex: "#294200")
    static let scaleGreen800 = UIColor(hex: "#192900")
    static let scaleYellow50 = UIColor(hex: "#FEFAF0")
    static let scaleYellow100 = UIColor(hex: "#FCEBC5")
    static let scaleYellow200 = UIColor(hex: "#F8D072")
    static let scaleYellow500 = UIColor(hex: "#F5BF40")
    static let scaleYellow600 = UIColor(hex: "#DA9C0B")
    static let scaleYellow700 = UIColor(hex: "#795706")
    static let scaleYellow800 = UIColor(hex: "#443104")
    static let scaleRed50 = UIColor(hex: "#FCF3F2")
    static let scaleRed100 = UIColor(hex: "#F4D1CD")
    static let scaleRed200 = UIColor(hex: "#EBAAA3")
    static let scaleRed500 = UIColor(hex: "#D13D2E")
    static let scaleRed600 = UIColor(hex: "#8E2A1F")
    static let scaleRed700 = UIColor(hex: "#712219")
    static let scaleRed800 = UIColor(hex: "#471510")
    static let scalePurple50 = UIColor(hex: "#F7F2FC")
    static let scalePurple100 = UIColor(hex: "#DCC9F3")
    static let scalePurple200 = UIColor(hex: "#AB7DE3")
    static let scalePurple500 = UIColor(hex: "#772ED1")
    static let scalePurple600 = UIColor(hex: "#5D24A3")
    static let scalePurple700 = UIColor(hex: "#4F1E8A")
    static let scalePurple800 = UIColor(hex: "#301254")
    static let neutralGrey00 = UIColor(hex: "#FFFFFF")
    static let neutralGrey50 = UIColor(hex: "#FCFDFD")
    static let neutralGrey100 = UIColor(hex: "#F7F8F8")
    static let neutralGrey200 = UIColor(hex: "#F4F5F5")
    static let neutralGrey300 = UIColor(hex: "#DFE2E2")
    static let neutralGrey400 = UIColor(hex: "#C9CFCF")
    static let neutralGrey500 = UIColor(hex: "#949E9E")
    static let neutralGrey600 = UIColor(hex: "#667070")
    static let neutralGrey700 = UIColor(hex: "#444B4B")
    static let neutralGrey800 = UIColor(hex: "#1F2323")
    static let neutralGrey900 = UIColor(hex: "#131515")
    static let surfaceApp = UIColor(hex: "#FFFFFF")
    static let surfacePage = UIColor(hex: "#FCFDFD")
    static let surfaceRow = UIColor(hex: "#FFFFFF")
    static let surfaceRowHover = UIColor(hex: "#EBF2F7")
    static let surfaceRowVisited = UIColor(hex: "#FCFDFD")
    static let surfaceTableHeader = UIColor(hex: "#F7F8F8")
    static let feedbackInfo = UIColor(hex: "#7DAFD6")
    static let feedbackSuccess = UIColor(hex: "#63A100")
    static let feedbackWarning = UIColor(hex: "#E6A200")
    static let feedbackAlert = UIColor(hex: "#AE2700")
    static let data1 = UIColor(hex: "#9ACBE5")
    static let data2 = UIColor(hex: "#FFAF97")
    static let data3 = UIColor(hex: "#C4DEF3")
    static let data4 = UIColor(hex: "#A7ADB2")
    static let data5 = UIColor(hex: "#0F69AA")
    static let data6 = UIColor(hex: "#C1674D")
    static let data7 = UIColor(hex: "#1F5077")
    static let data8 = UIColor(hex: "#394751")
    static let data9 = UIColor(hex: "#CDE5F2")
    static let data10 = UIColor(hex: "#FFD9CE")
    static let statusOngoing = UIColor(hex: "#7DAFD6")
    static let statusFinished = UIColor(hex: "#63A100")
    static let statusNotAccessible = UIColor(hex: "#E6A200")
    static let statusIncomplete = UIColor(hex: "#E6A200")
    static let statusDelayed = UIColor(hex: "#E6A200")
    static let statusCancelled = UIColor(hex: "#AE2700")
    static let statusTimeout = UIColor(hex: "#AE2700")
    static let statusError = UIColor(hex: "#AE2700")
    static let statusInaccessible = UIColor(hex: "#AE2700")
    static let statusTooManyInaccessible = UIColor(hex: "#AE2700")
    static let textPrimary = UIColor(hex: "#121F28")
    static let textSecondary = UIColor(hex: "#657078")
    static let textDisabled = UIColor(hex: "#A7ADB2")
    static let textPlaceholder = UIColor(hex: "#A7ADB2")
    static let textWhite = UIColor(hex: "#FFFFFF")
    static let textInverse = UIColor(hex: "#FFFFFF")
    static let textOnAccent = UIColor(hex: "#FFFFFF")
    static let textLink = UIColor(hex: "#0066CC")
    static let textSuccess = UIColor(hex: "#2F7D2C")
    static let textWarning = UIColor(hex: "#8E6800")
    static let textError = UIColor(hex: "#B0291E")
    static let btnNeutral100 = UIColor(hex: "#F7F8F8")
    static let btnNeutral300 = UIColor(hex: "#DFE2E2")
    static let btnNeutral600 = UIColor(hex: "#667070")
    static let btnNeutral700 = UIColor(hex: "#444B4B")
    static let btnNeutral800 = UIColor(hex: "#202323")
    static let btnPrimary50 = UIColor(hex: "#EBF2F7")
    static let btnPrimary600 = UIColor(hex: "#0F69AA")
    static let btnPrimary700 = UIColor(hex: "#024A72")
    static let btnSuccess50 = UIColor(hex: "#EFF7E5")
    static let btnSuccess600 = UIColor(hex: "#406800")
    static let btnSuccess700 = UIColor(hex: "#284000")
    static let btnWarning50 = UIColor(hex: "#FFFBF0")
    static let btnWarning600 = UIColor(hex: "#E6A200")
    static let btnWarning700 = UIColor(hex: "#805A00")
    static let btnError50 = UIColor(hex: "#FFF0EF")
    static let btnError600 = UIColor(hex: "#AE2700")
    static let btnError700 = UIColor(hex: "#881F00")
}

// MARK: - Spacing

extension CGFloat {
    static let space1: CGFloat = 4
    static let space2: CGFloat = 8
    static let space3: CGFloat = 12
    static let space4: CGFloat = 16
    static let space5: CGFloat = 20
    static let space6: CGFloat = 24
    static let space8: CGFloat = 32
    static let space12: CGFloat = 48
    static let space16: CGFloat = 64
}

// MARK: - Z-Index Layers

extension Int {
    static let zBase: Int = 0
    static let zSticky: Int = 10
    static let zDropdown: Int = 20
    static let zOverlay: Int = 30
    static let zSidebar: Int = 40
    static let zModal: Int = 50
    static let zToast: Int = 60
}

// MARK: - Motion Durations (TimeInterval, seconds)

extension TimeInterval {
    static let motionDurationInstant: TimeInterval = 0.075
    static let motionDurationSnap: TimeInterval = 0.1
    static let motionDurationDefault: TimeInterval = 0.15
    static let motionDurationEmphasis: TimeInterval = 0.2
    static let motionDurationSpatial: TimeInterval = 0.3
}
