// Design System — Tokens used by this component
// Auto-generated by scripts/export-tokens.js — do not edit by hand.
// Assumes UIColor(hex:) initializer exists in your project.

import UIKit

// MARK: - Colors

extension UIColor {
    static let brandPrimary500 = UIColor(hex: "#1383D4")
    static let brandPrimary600 = UIColor(hex: "#0F69A9")
    static let scaleRed600 = UIColor(hex: "#8E2A1F")
    static let neutralGrey300 = UIColor(hex: "#DFE2E2")
    static let neutralGrey500 = UIColor(hex: "#949E9E")
    static let surfaceRow = UIColor(hex: "#FFFFFF")
    static let surfaceRowHover = UIColor(hex: "#EBF2F7")
    static let textPrimary = UIColor(hex: "#121F28")
    static let textSecondary = UIColor(hex: "#657078")
    static let textDisabled = UIColor(hex: "#A7ADB2")
}

// MARK: - Sizing (CGFloat)

extension CGFloat {
    // Spacing
    static let space2: CGFloat = 8
    static let space9: CGFloat = 36
    static let space3: CGFloat = 12
    static let space1: CGFloat = 4
    static let space4: CGFloat = 16
    static let space10: CGFloat = 40
    static let space6: CGFloat = 24
    static let space5: CGFloat = 20
    static let space8: CGFloat = 32

    // Radius
    static let radiusMd: CGFloat = 6
    static let radiusXl: CGFloat = 12

    // Border width
    static let borderWidth1: CGFloat = 1

    // Font size
    static let fontSize10: CGFloat = 10
    static let fontSize11: CGFloat = 11
    static let fontSize14: CGFloat = 14
    static let fontSize15: CGFloat = 15

    // Focus ring width
    static let ringWidth2: CGFloat = 2
}

// MARK: - Font weights (use UIFont.Weight directly)
// font-weight-medium → .medium   (CSS 500)
// font-weight-semibold → .semibold   (CSS 600)
