// Design System — Tokens used by this component
// Auto-generated by scripts/export-tokens.js — do not edit by hand.
// Assumes UIColor(hex:) initializer exists in your project.

import UIKit

// MARK: - Colors

extension UIColor {
    static let brandPrimary500 = UIColor(hex: "#1383D4")
    static let brandPrimary600 = UIColor(hex: "#0F69A9")
    static let scaleYellow50 = UIColor(hex: "#FEFAF0")
    static let scaleYellow500 = UIColor(hex: "#F5BF40")
    static let scaleYellow700 = UIColor(hex: "#795706")
    static let scaleRed50 = UIColor(hex: "#FCF3F2")
    static let scaleRed500 = UIColor(hex: "#D13D2E")
    static let scaleRed600 = UIColor(hex: "#8E2A1F")
    static let scalePurple50 = UIColor(hex: "#F7F2FC")
    static let scalePurple500 = UIColor(hex: "#772ED1")
    static let scalePurple600 = UIColor(hex: "#5D24A3")
    static let neutralGrey100 = UIColor(hex: "#F7F8F8")
    static let neutralGrey900 = UIColor(hex: "#131515")
    static let surfaceApp = UIColor(hex: "#FFFFFF")
    static let textPrimary = UIColor(hex: "#121F28")
    static let textSecondary = UIColor(hex: "#657078")
    static let textDisabled = UIColor(hex: "#A7ADB2")
    static let textInverse = UIColor(hex: "#FFFFFF")
}

// MARK: - Sizing (CGFloat)

extension CGFloat {
    // Spacing
    static let space3: CGFloat = 12
    static let space2: CGFloat = 8
    static let space1: CGFloat = 4
    static let space5: CGFloat = 20
    static let space4: CGFloat = 16
    static let space6: CGFloat = 24
    static let space10: CGFloat = 40
    static let space8: CGFloat = 32
    static let space12: CGFloat = 48
    static let space16: CGFloat = 64

    // Radius
    static let radiusBase: CGFloat = 4
    static let radiusMd: CGFloat = 6
    static let radiusLg: CGFloat = 8
    static let radiusXl: CGFloat = 12
    static let radiusFull: CGFloat = 9999

    // Border width
    static let borderWidth1: CGFloat = 1

    // Font size
    static let fontSize10: CGFloat = 10
    static let fontSize11: CGFloat = 11
    static let fontSize12: CGFloat = 12
    static let fontSize13: CGFloat = 13
    static let fontSize14: CGFloat = 14
    static let fontSize15: CGFloat = 15
}

// MARK: - Font weights (use UIFont.Weight directly)
// font-weight-medium → .medium   (CSS 500)
// font-weight-semibold → .semibold   (CSS 600)
