#!/usr/bin/env node
/**
 * Token export — reads design tokens from app/globals.css and writes
 * platform-specific outputs to public/tokens/.
 *
 * Outputs:
 *   public/tokens/tokens.css   — raw CSS variables (copied from :root)
 *   public/tokens/tokens.swift — Swift / iOS extensions
 *   public/tokens/tokens.xml   — Android resources
 *
 * Run manually: `npm run tokens`
 * Auto-runs:   `npm run build` (via the prebuild script in package.json)
 */

const fs   = require("fs");
const path = require("path");

const ROOT     = path.resolve(__dirname, "..");
const SRC_CSS  = path.join(ROOT, "app", "globals.css");
const OUT_DIR  = path.join(ROOT, "public", "tokens");

// ── 1. Spacing scale (mirrors components/styleguide/spacing-data.ts) ──────

const SPACING = [
  ["space-1",   4],
  ["space-2",   8],
  ["space-3",  12],
  ["space-4",  16],
  ["space-5",  20],
  ["space-6",  24],
  ["space-8",  32],
  ["space-12", 48],
  ["space-16", 64],
];

// ── 2. Read + parse :root block from globals.css ──────────────────────────

const css = fs.readFileSync(SRC_CSS, "utf8");

const ROOT_BLOCK = /:root,\s*\[data-s4e-theme="light"\]\s*\{([\s\S]*?)\n\}/m;
const match      = css.match(ROOT_BLOCK);
if (!match) {
  console.error("export-tokens: could not find :root block in globals.css");
  process.exit(1);
}

const rootBody = match[1];

// Parse each `--token: value;` line
const tokens = [];
const TOKEN_RE = /--([a-z0-9-]+)\s*:\s*([^;]+);/g;
let m;
while ((m = TOKEN_RE.exec(rootBody)) !== null) {
  const name  = m[1].trim();
  const value = m[2].trim();
  if (!name.startsWith("s4e-")) continue;
  tokens.push({ name, value });
}

// Build maps by category
const colors    = [];   // solid hex tokens — Swift UIColor + Android color
const zIndex    = [];   // numeric integers — Android dimen
const durations = [];   // Xms → Swift TimeInterval + Android dimen

for (const { name, value } of tokens) {
  const localName = name.replace(/^s4e-/, "");

  // Skip shadow / easing (multi-value, format-specific)
  if (localName.startsWith("shadow-"))      continue;
  if (localName.startsWith("motion-ease-")) continue;

  // Z-index: numeric integer
  if (localName.startsWith("z-")) {
    zIndex.push({ name: localName, value: Number(value) });
    continue;
  }

  // Motion duration: "150ms"
  if (localName.startsWith("motion-duration-")) {
    const ms = parseInt(value, 10);
    durations.push({ name: localName, ms });
    continue;
  }

  // Solid color (#hex)
  const hex = value.match(/^#[0-9a-fA-F]{6}$/);
  if (hex) {
    colors.push({ name: localName, hex: value.toUpperCase() });
    continue;
  }

  // rgba colors with alpha — skip (Swift/Android need different handling)
}

// ── 3. Naming helpers ─────────────────────────────────────────────────────

function toCamel(name) {
  return name
    .split("-")
    .map((p, i) => (i === 0 ? p : p[0].toUpperCase() + p.slice(1)))
    .join("");
}

function toSnake(name) {
  return name.replace(/-/g, "_");
}

// ── 4. CSS output (raw copy of :root block, isolated to a single file) ────

function buildCss() {
  let out = "";
  out += "/* Design System — Tokens (CSS Custom Properties)\n";
  out += " * Auto-generated by scripts/export-tokens.js — do not edit by hand.\n";
  out += " * Source: app/globals.css (:root block)\n";
  out += " */\n\n";
  out += ":root {\n";
  for (const { name, value } of tokens) {
    out += `  --${name}: ${value};\n`;
  }
  out += "}\n";
  return out;
}

// ── 5. Swift / iOS output ─────────────────────────────────────────────────

function buildSwift() {
  let out = "";
  out += "// Design System — Tokens for iOS\n";
  out += "// Auto-generated by scripts/export-tokens.js — do not edit by hand.\n";
  out += "//\n";
  out += "// Usage:\n";
  out += "//   view.backgroundColor = .severityCritical\n";
  out += "//   constraint.constant  = .space4\n";
  out += "//\n";
  out += "// UIColor(hex:) is assumed to exist in your project. If not, add it once:\n";
  out += "//   extension UIColor {\n";
  out += "//     convenience init(hex: String) {\n";
  out += "//       let v = UInt64(hex.dropFirst(), radix: 16) ?? 0\n";
  out += "//       self.init(red:   CGFloat((v >> 16) & 0xff) / 255,\n";
  out += "//                 green: CGFloat((v >>  8) & 0xff) / 255,\n";
  out += "//                 blue:  CGFloat( v        & 0xff) / 255,\n";
  out += "//                 alpha: 1)\n";
  out += "//     }\n";
  out += "//   }\n\n";
  out += "import UIKit\n\n";

  // Colors
  out += "// MARK: - Colors\n\n";
  out += "extension UIColor {\n";
  for (const { name, hex } of colors) {
    out += `    static let ${toCamel(name)} = UIColor(hex: "${hex}")\n`;
  }
  out += "}\n\n";

  // Spacing
  out += "// MARK: - Spacing\n\n";
  out += "extension CGFloat {\n";
  for (const [name, px] of SPACING) {
    out += `    static let ${toCamel(name)}: CGFloat = ${px}\n`;
  }
  out += "}\n\n";

  // Z-index layers
  out += "// MARK: - Z-Index Layers\n\n";
  out += "extension Int {\n";
  for (const { name, value } of zIndex) {
    out += `    static let ${toCamel(name)}: Int = ${value}\n`;
  }
  out += "}\n\n";

  // Motion durations (seconds for Swift)
  out += "// MARK: - Motion Durations (TimeInterval, seconds)\n\n";
  out += "extension TimeInterval {\n";
  for (const { name, ms } of durations) {
    const seconds = (ms / 1000).toFixed(3).replace(/0+$/, "").replace(/\.$/, "");
    out += `    static let ${toCamel(name)}: TimeInterval = ${seconds}\n`;
  }
  out += "}\n";

  return out;
}

// ── 6. Android XML output ─────────────────────────────────────────────────

function escapeXml(s) {
  return s.replace(/&/g, "&amp;").replace(/</g, "&lt;").replace(/>/g, "&gt;");
}

function buildAndroidXml() {
  let out = "";
  out += '<?xml version="1.0" encoding="utf-8"?>\n';
  out += "<!-- Design System — Tokens for Android\n";
  out += "     Auto-generated by scripts/export-tokens.js — do not edit by hand.\n";
  out += "     Drop into res/values/design_tokens.xml. -->\n";
  out += "<resources>\n\n";

  out += "    <!-- Colors -->\n";
  for (const { name, hex } of colors) {
    out += `    <color name="${toSnake(name)}">${escapeXml(hex)}</color>\n`;
  }

  out += "\n    <!-- Spacing -->\n";
  for (const [name, px] of SPACING) {
    out += `    <dimen name="${toSnake(name)}">${px}dp</dimen>\n`;
  }

  out += "\n    <!-- Z-Index Layers -->\n";
  for (const { name, value } of zIndex) {
    out += `    <integer name="${toSnake(name)}">${value}</integer>\n`;
  }

  out += "\n    <!-- Motion Durations (milliseconds) -->\n";
  for (const { name, ms } of durations) {
    out += `    <integer name="${toSnake(name)}">${ms}</integer>\n`;
  }

  out += "\n</resources>\n";
  return out;
}

// ── 7. Write files ────────────────────────────────────────────────────────

fs.mkdirSync(OUT_DIR, { recursive: true });

const targets = [
  ["tokens.css",   buildCss()],
  ["tokens.swift", buildSwift()],
  ["tokens.xml",   buildAndroidXml()],
];

for (const [filename, content] of targets) {
  fs.writeFileSync(path.join(OUT_DIR, filename), content, "utf8");
}

console.log("✓ export-tokens —",
  colors.length, "colors,",
  SPACING.length, "spacing,",
  zIndex.length, "z-index,",
  durations.length, "durations →",
  path.relative(ROOT, OUT_DIR) + "/");
