#!/usr/bin/env node
/**
 * Token export — generates token files from app/globals.css.
 *
 * Outputs:
 *   public/tokens/<slug>/tokens.css   — only the tokens used by <slug>
 *   public/tokens/<slug>/tokens.swift
 *   public/tokens/<slug>/tokens.xml
 *
 * Each <slug> matches a route under app/styleguide/<slug>. The script scans
 * the matching sections/<slug>/ source (and the page itself) for s4e-*
 * token references and emits a per-component subset.
 *
 * Run manually: `npm run tokens`
 * Auto-runs:   `npm run build` (via the prebuild script in package.json)
 */

const fs   = require("fs");
const path = require("path");

const ROOT       = path.resolve(__dirname, "..");
const SRC_CSS    = path.join(ROOT, "app", "globals.css");
const STYLEGUIDE = path.join(ROOT, "app", "styleguide");
const SECTIONS   = path.join(ROOT, "sections");
const OUT_DIR    = path.join(ROOT, "public", "tokens");

// ── Spacing scale (mirrors components/styleguide/spacing-data.ts) ─────────

const SPACING = [
  ["space-1",   4],
  ["space-2",   8],
  ["space-3",  12],
  ["space-4",  16],
  ["space-5",  20],
  ["space-6",  24],
  ["space-8",  32],
  ["space-12", 48],
  ["space-16", 64],
];

const SPACING_INDEX = new Map(SPACING.map((s) => [s[0], s[1]]));

// ── Read + parse :root block from globals.css ─────────────────────────────

const css = fs.readFileSync(SRC_CSS, "utf8");

const ROOT_BLOCK = /:root,\s*\[data-s4e-theme="light"\]\s*\{([\s\S]*?)\n\}/m;
const match      = css.match(ROOT_BLOCK);
if (!match) {
  console.error("export-tokens: could not find :root block in globals.css");
  process.exit(1);
}
const rootBody = match[1];

// Parse all --s4e-* tokens
const ALL_TOKENS = [];
const TOKEN_RE   = /--([a-z0-9-]+)\s*:\s*([^;]+);/g;
let m;
while ((m = TOKEN_RE.exec(rootBody)) !== null) {
  const name  = m[1].trim();
  const value = m[2].trim();
  if (!name.startsWith("s4e-")) continue;
  ALL_TOKENS.push({ name, value });
}

// Categorize one token: returns "color" | "z" | "duration" | null (skip)
function categorize({ name, value }) {
  const local = name.replace(/^s4e-/, "");
  if (local.startsWith("shadow-"))      return null;
  if (local.startsWith("motion-ease-")) return null;
  if (local.startsWith("z-"))               return "z";
  if (local.startsWith("motion-duration-")) return "duration";
  if (/^#[0-9a-fA-F]{6}$/.test(value))      return "color";
  return null; // rgba, etc.
}

// ── Naming helpers ────────────────────────────────────────────────────────

function toCamel(name) {
  return name.split("-").map((p, i) => (i === 0 ? p : p[0].toUpperCase() + p.slice(1))).join("");
}
function toSnake(name) { return name.replace(/-/g, "_"); }
function escapeXml(s)  { return s.replace(/&/g, "&amp;").replace(/</g, "&lt;").replace(/>/g, "&gt;"); }

// ── File walker — collect source files for a given slug ───────────────────

function walk(dir, out = []) {
  let entries;
  try { entries = fs.readdirSync(dir, { withFileTypes: true }); }
  catch { return out; }
  for (const e of entries) {
    const p = path.join(dir, e.name);
    if (e.isDirectory()) walk(p, out);
    else if (/\.(tsx?|jsx?)$/.test(e.name)) out.push(p);
  }
  return out;
}

function sourcesForSlug(slug) {
  const files = [];
  walk(path.join(SECTIONS, slug), files);
  const pageFile = path.join(STYLEGUIDE, slug, "page.tsx");
  if (fs.existsSync(pageFile)) files.push(pageFile);
  return files;
}

// ── Token extraction from source ──────────────────────────────────────────

function extractTokensUsed(files) {
  const used = new Set();
  const spaces = new Set();
  for (const file of files) {
    const text = fs.readFileSync(file, "utf8");

    // Tailwind class patterns: text-s4e-X, bg-s4e-X, border-s4e-X, ring-s4e-X,
    // shadow-s4e-X, fill-s4e-X, stroke-s4e-X, divide-s4e-X, ...
    const classMatches = text.matchAll(/(?:^|[^a-z])s4e-([a-z0-9-]+)/g);
    for (const m of classMatches) used.add(`s4e-${m[1]}`);

    // CSS var() references
    const vars = text.matchAll(/var\(--s4e-([a-z0-9-]+)\)/g);
    for (const m of vars) used.add(`s4e-${m[1]}`);

    // Spacing — Tailwind class numbers like p-4, gap-2, mt-6
    const spaceMatches = text.matchAll(/(?:^|[^a-z])(?:p|px|py|pt|pr|pb|pl|m|mx|my|mt|mr|mb|ml|gap|space-y|space-x|w|h|min-w|min-h|max-w|max-h)-(\d+(?:\.\d+)?)\b/g);
    for (const m of spaceMatches) {
      const n = m[1];
      if (SPACING_INDEX.has(`space-${n}`)) spaces.add(`space-${n}`);
    }
  }
  return { tokenNames: used, spaceNames: spaces };
}

// ── Builders for the three output formats ─────────────────────────────────

function buildCss(tokens, spaces) {
  let out = "";
  out += "/* Design System — Tokens used by this component\n";
  out += " * Auto-generated by scripts/export-tokens.js — do not edit by hand.\n";
  out += " */\n\n:root {\n";
  for (const { name, value } of tokens) {
    out += `  --${name}: ${value};\n`;
  }
  for (const n of spaces) {
    out += `  --${n}: ${SPACING_INDEX.get(n)}px;\n`;
  }
  out += "}\n";
  return out;
}

function buildSwift(tokens, spaces) {
  const colors    = tokens.filter((t) => categorize(t) === "color");
  const zIndex    = tokens.filter((t) => categorize(t) === "z");
  const durations = tokens.filter((t) => categorize(t) === "duration");

  let out = "";
  out += "// Design System — Tokens used by this component\n";
  out += "// Auto-generated by scripts/export-tokens.js — do not edit by hand.\n";
  out += "// Assumes UIColor(hex:) initializer exists in your project.\n\n";
  out += "import UIKit\n";

  if (colors.length) {
    out += "\n// MARK: - Colors\n\nextension UIColor {\n";
    for (const { name, value } of colors) {
      out += `    static let ${toCamel(name.replace(/^s4e-/, ""))} = UIColor(hex: "${value.toUpperCase()}")\n`;
    }
    out += "}\n";
  }
  if (spaces.size) {
    out += "\n// MARK: - Spacing\n\nextension CGFloat {\n";
    for (const n of spaces) {
      out += `    static let ${toCamel(n)}: CGFloat = ${SPACING_INDEX.get(n)}\n`;
    }
    out += "}\n";
  }
  if (zIndex.length) {
    out += "\n// MARK: - Z-Index Layers\n\nextension Int {\n";
    for (const { name, value } of zIndex) {
      out += `    static let ${toCamel(name.replace(/^s4e-/, ""))}: Int = ${Number(value)}\n`;
    }
    out += "}\n";
  }
  if (durations.length) {
    out += "\n// MARK: - Motion Durations (TimeInterval, seconds)\n\nextension TimeInterval {\n";
    for (const { name, value } of durations) {
      const ms = parseInt(value, 10);
      const s  = (ms / 1000).toFixed(3).replace(/0+$/, "").replace(/\.$/, "");
      out += `    static let ${toCamel(name.replace(/^s4e-/, ""))}: TimeInterval = ${s}\n`;
    }
    out += "}\n";
  }
  return out;
}

function buildAndroidXml(tokens, spaces) {
  const colors    = tokens.filter((t) => categorize(t) === "color");
  const zIndex    = tokens.filter((t) => categorize(t) === "z");
  const durations = tokens.filter((t) => categorize(t) === "duration");

  let out = '<?xml version="1.0" encoding="utf-8"?>\n';
  out += "<!-- Design System — Tokens used by this component\n";
  out += "     Auto-generated by scripts/export-tokens.js — do not edit by hand. -->\n";
  out += "<resources>\n";

  if (colors.length) {
    out += "\n    <!-- Colors -->\n";
    for (const { name, value } of colors) {
      out += `    <color name="${toSnake(name.replace(/^s4e-/, ""))}">${escapeXml(value.toUpperCase())}</color>\n`;
    }
  }
  if (spaces.size) {
    out += "\n    <!-- Spacing -->\n";
    for (const n of spaces) {
      out += `    <dimen name="${toSnake(n)}">${SPACING_INDEX.get(n)}dp</dimen>\n`;
    }
  }
  if (zIndex.length) {
    out += "\n    <!-- Z-Index Layers -->\n";
    for (const { name, value } of zIndex) {
      out += `    <integer name="${toSnake(name.replace(/^s4e-/, ""))}">${Number(value)}</integer>\n`;
    }
  }
  if (durations.length) {
    out += "\n    <!-- Motion Durations (milliseconds) -->\n";
    for (const { name, value } of durations) {
      const ms = parseInt(value, 10);
      out += `    <integer name="${toSnake(name.replace(/^s4e-/, ""))}">${ms}</integer>\n`;
    }
  }
  out += "\n</resources>\n";
  return out;
}

// ── Main: walk slugs under app/styleguide/ ────────────────────────────────

function isSlugDir(name) {
  return !name.startsWith("_") && !name.startsWith(".") && !name.endsWith(".tsx") && !name.endsWith(".ts");
}

const slugs = fs.readdirSync(STYLEGUIDE, { withFileTypes: true })
  .filter((e) => e.isDirectory() && isSlugDir(e.name))
  .map((e) => e.name);

let total = 0;
fs.mkdirSync(OUT_DIR, { recursive: true });

for (const slug of slugs) {
  const sources = sourcesForSlug(slug);
  if (sources.length === 0) continue;

  const { tokenNames, spaceNames } = extractTokensUsed(sources);
  const tokens = ALL_TOKENS.filter((t) => tokenNames.has(t.name));

  // Skip slugs that don't actually use any design-system token
  if (tokens.length === 0 && spaceNames.size === 0) continue;

  const outDir = path.join(OUT_DIR, slug);
  fs.mkdirSync(outDir, { recursive: true });

  fs.writeFileSync(path.join(outDir, "tokens.css"),   buildCss(tokens, spaceNames));
  fs.writeFileSync(path.join(outDir, "tokens.swift"), buildSwift(tokens, spaceNames));
  fs.writeFileSync(path.join(outDir, "tokens.xml"),   buildAndroidXml(tokens, spaceNames));

  total++;
  console.log(`  ${slug}: ${tokens.length} tokens + ${spaceNames.size} spacing`);
}

console.log(`✓ export-tokens — generated per-component tokens for ${total} slugs → ${path.relative(ROOT, OUT_DIR)}/`);
