// Design System — Tokens used by this component
// Auto-generated by scripts/export-tokens.js — do not edit by hand.
// Assumes UIColor(hex:) initializer exists in your project.

import UIKit

// MARK: - Colors

extension UIColor {
    static let brandPrimary500 = UIColor(hex: "#1383D4")
    static let neutralGrey100 = UIColor(hex: "#F7F8F8")
    static let surfaceApp = UIColor(hex: "#FFFFFF")
    static let textPrimary = UIColor(hex: "#121F28")
    static let textSecondary = UIColor(hex: "#657078")
    static let textDisabled = UIColor(hex: "#A7ADB2")
    static let textWhite = UIColor(hex: "#FFFFFF")
    static let btnPrimary600 = UIColor(hex: "#0F69AA")
    static let btnPrimary700 = UIColor(hex: "#024A72")
}

// MARK: - Sizing (CGFloat)

extension CGFloat {
    // Spacing
    static let space2: CGFloat = 8
    static let space4: CGFloat = 16
    static let space8: CGFloat = 32
    static let space3: CGFloat = 12
    static let space9: CGFloat = 36
    static let space10: CGFloat = 40
    static let space6: CGFloat = 24

    // Radius
    static let radiusSm: CGFloat = 2
    static let radiusMd: CGFloat = 6
    static let radiusLg: CGFloat = 8
    static let radiusXl: CGFloat = 12
    static let radiusFull: CGFloat = 9999

    // Border width
    static let borderWidth1: CGFloat = 1

    // Font size
    static let fontSize9: CGFloat = 9
    static let fontSize10: CGFloat = 10
    static let fontSize11: CGFloat = 11
    static let fontSize13: CGFloat = 13
    static let fontSize15: CGFloat = 15
}

// MARK: - Font weights (use UIFont.Weight directly)
// font-weight-medium → .medium   (CSS 500)
// font-weight-semibold → .semibold   (CSS 600)
// font-weight-bold → .bold   (CSS 700)
