import type React from "react";
import {
  SingleScan,
} from "@/components/icons/single-scan";
import { FullScan } from "@/components/icons/full-scan";
import { LightScan } from "@/components/icons/light-scan";
import { Crawler } from "@/components/icons/crawler";
import { ContinuousScan } from "@/components/icons/continuous-scan";
import {
  // Layout
  LayoutDashboard, LayoutGrid, Sidebar, SidebarOpen, SidebarClose,
  PanelLeft, PanelRight, PanelTop, PanelBottom, Columns2, Rows2,
  Table, Table2, List, ListOrdered, ListFilter, AlignLeft, AlignCenter, AlignRight,
  Maximize, Minimize, Maximize2, Minimize2,
  // Charts
  BarChart2, BarChart3, BarChart4, LineChart, PieChart, AreaChart,
  TrendingUp, TrendingDown, Activity, Gauge, Percent,
  // Security
  Shield, ShieldCheck, ShieldAlert, ShieldX, ShieldOff, ShieldEllipsis,
  Lock, LockOpen, LockKeyhole, Key, KeyRound, Fingerprint,
  Scan, ScanLine, Eye, EyeOff, Bug, Siren, AlertTriangle, Skull,
  // Education
  BookOpen, Book, BookMarked, BookText, BookCopy, GraduationCap,
  Library, Lightbulb, Notebook, NotebookPen, School,
  // Development
  Code, Code2, Terminal,
  GitBranch, GitCommit, GitMerge, GitPullRequest, GitFork,
  Package, Package2, Braces, FileCode, FileCode2, Wrench,
  // Arrows
  ArrowUp, ArrowDown, ArrowLeft, ArrowRight,
  ArrowUpRight, ArrowDownRight, ArrowUpLeft, ArrowDownLeft,
  ArrowRightLeft, ArrowUpDown, ArrowLeftRight,
  ChevronUp, ChevronDown, ChevronLeft, ChevronRight,
  ChevronsUp, ChevronsDown, ChevronsLeft, ChevronsRight, ChevronsUpDown,
  CornerUpRight, CornerDownRight, RefreshCw, RotateCw, Move, MoveRight, MoveLeft,
  // Finance & commerce
  DollarSign, CircleDollarSign, Euro, CreditCard, Wallet,
  ShoppingCart, ShoppingBag, Receipt, Banknote, BadgePercent, Coins, Store,
  // Access
  User, Users, UserCheck, UserX, UserPlus, UserMinus, UserCog, LogIn, LogOut, KeySquare,
  // Data
  Database, Server, HardDrive, Cpu,
  Network, Globe, Wifi, WifiOff, Signal, CloudUpload, CloudDownload, Cloud,
  FolderOpen, Folder, FolderClosed,
  // Shapes
  Circle, CircleDot, Square, Triangle, Diamond, Hexagon, Octagon,
  Star, Minus, Plus, X, Slash, Dot,
  // General
  Home, Settings, Settings2, Bell, BellOff, BellRing,
  Search, Filter, SortAsc, SortDesc, MoreHorizontal, MoreVertical, Menu, Hash, Tag,
  Bookmark, Heart, ThumbsUp, ThumbsDown, Share, Share2,
  ExternalLink, Link, Link2, Link2Off, Copy, Clipboard, ClipboardCheck, ClipboardList,
  // Items & Feedback
  CircleCheck, CircleX, CircleAlert, Info, CircleHelp,
  MessageSquare, MessageCircle, Inbox, Archive, Trash, Trash2,
  Flag, Zap, ZapOff, Check, Loader, LoaderCircle, Send, Reply, Forward,
  // Maps & Location
  MapPin, MapPinOff, Map, Navigation, Navigation2, Compass,
  Building, Building2, Hotel, Castle, Mountain,
  // Users
  UserRound, Users2, Contact, Crown, BadgeCheck, BadgeX,
  // Items & Services
  Monitor, Laptop, Smartphone, Tablet, Printer,
  Keyboard, Mouse, Headphones, Camera, CameraOff, Tv,
  // Transport
  Car, Truck, Bus, Train, Plane, PlaneLanding, PlaneTakeoff, Ship, Bike, Rocket,
  // Communication
  Phone, PhoneCall, PhoneOff, PhoneIncoming, PhoneOutgoing,
  Video, VideoOff, Mic, MicOff,
  Mail, MailOpen, MailCheck, Radio, Rss,
  // Time
  Clock, Timer, TimerOff, AlarmClock, Calendar, CalendarDays,
  CalendarCheck, CalendarX, Hourglass, Watch,
} from "lucide-react";

export type IconComponent = React.ComponentType<{ size?: number; className?: string }>;
export type IconEntry = { name: string; icon: IconComponent };
export type IconGroup = { name: string; icons: IconEntry[] };

export const iconGroups: IconGroup[] = [
  {
    name: "Custom",
    icons: [
      { name: "SingleScan", icon: SingleScan },
      { name: "FullScan", icon: FullScan },
      { name: "LightScan", icon: LightScan },
      { name: "Crawler", icon: Crawler },
      { name: "ContinuousScan", icon: ContinuousScan },
    ],
  },
  {
    name: "Layout",
    icons: [
      { name: "LayoutDashboard", icon: LayoutDashboard },
      { name: "LayoutGrid", icon: LayoutGrid },
      { name: "Sidebar", icon: Sidebar },
      { name: "SidebarOpen", icon: SidebarOpen },
      { name: "SidebarClose", icon: SidebarClose },
      { name: "PanelLeft", icon: PanelLeft },
      { name: "PanelRight", icon: PanelRight },
      { name: "PanelTop", icon: PanelTop },
      { name: "PanelBottom", icon: PanelBottom },
      { name: "Columns2", icon: Columns2 },
      { name: "Rows2", icon: Rows2 },
      { name: "Table", icon: Table },
      { name: "Table2", icon: Table2 },
      { name: "List", icon: List },
      { name: "ListOrdered", icon: ListOrdered },
      { name: "ListFilter", icon: ListFilter },
      { name: "AlignLeft", icon: AlignLeft },
      { name: "AlignCenter", icon: AlignCenter },
      { name: "AlignRight", icon: AlignRight },
      { name: "Maximize", icon: Maximize },
      { name: "Minimize", icon: Minimize },
      { name: "Maximize2", icon: Maximize2 },
      { name: "Minimize2", icon: Minimize2 },
    ],
  },
  {
    name: "Charts",
    icons: [
      { name: "BarChart2", icon: BarChart2 },
      { name: "BarChart3", icon: BarChart3 },
      { name: "BarChart4", icon: BarChart4 },
      { name: "LineChart", icon: LineChart },
      { name: "PieChart", icon: PieChart },
      { name: "AreaChart", icon: AreaChart },
      { name: "TrendingUp", icon: TrendingUp },
      { name: "TrendingDown", icon: TrendingDown },
      { name: "Activity", icon: Activity },
      { name: "Gauge", icon: Gauge },
      { name: "Percent", icon: Percent },
    ],
  },
  {
    name: "Security",
    icons: [
      { name: "Shield", icon: Shield },
      { name: "ShieldCheck", icon: ShieldCheck },
      { name: "ShieldAlert", icon: ShieldAlert },
      { name: "ShieldX", icon: ShieldX },
      { name: "ShieldOff", icon: ShieldOff },
      { name: "ShieldEllipsis", icon: ShieldEllipsis },
      { name: "Lock", icon: Lock },
      { name: "LockOpen", icon: LockOpen },
      { name: "LockKeyhole", icon: LockKeyhole },
      { name: "Key", icon: Key },
      { name: "KeyRound", icon: KeyRound },
      { name: "Fingerprint", icon: Fingerprint },
      { name: "Scan", icon: Scan },
      { name: "ScanLine", icon: ScanLine },
      { name: "Eye", icon: Eye },
      { name: "EyeOff", icon: EyeOff },
      { name: "Bug", icon: Bug },
      { name: "Siren", icon: Siren },
      { name: "AlertTriangle", icon: AlertTriangle },
      { name: "Skull", icon: Skull },
    ],
  },
  {
    name: "Education",
    icons: [
      { name: "BookOpen", icon: BookOpen },
      { name: "Book", icon: Book },
      { name: "BookMarked", icon: BookMarked },
      { name: "BookText", icon: BookText },
      { name: "BookCopy", icon: BookCopy },
      { name: "GraduationCap", icon: GraduationCap },
      { name: "Library", icon: Library },
      { name: "Lightbulb", icon: Lightbulb },
      { name: "Notebook", icon: Notebook },
      { name: "NotebookPen", icon: NotebookPen },
      { name: "School", icon: School },
    ],
  },
  {
    name: "Development",
    icons: [
      { name: "Code", icon: Code },
      { name: "Code2", icon: Code2 },
      { name: "Terminal", icon: Terminal },
      { name: "GitBranch", icon: GitBranch },
      { name: "GitCommit", icon: GitCommit },
      { name: "GitMerge", icon: GitMerge },
      { name: "GitPullRequest", icon: GitPullRequest },
      { name: "GitFork", icon: GitFork },
      { name: "Package", icon: Package },
      { name: "Package2", icon: Package2 },
      { name: "Braces", icon: Braces },
      { name: "FileCode", icon: FileCode },
      { name: "FileCode2", icon: FileCode2 },
      { name: "Wrench", icon: Wrench },
      { name: "Bug", icon: Bug },
    ],
  },
  {
    name: "Arrows",
    icons: [
      { name: "ArrowUp", icon: ArrowUp },
      { name: "ArrowDown", icon: ArrowDown },
      { name: "ArrowLeft", icon: ArrowLeft },
      { name: "ArrowRight", icon: ArrowRight },
      { name: "ArrowUpRight", icon: ArrowUpRight },
      { name: "ArrowDownRight", icon: ArrowDownRight },
      { name: "ArrowUpLeft", icon: ArrowUpLeft },
      { name: "ArrowDownLeft", icon: ArrowDownLeft },
      { name: "ArrowRightLeft", icon: ArrowRightLeft },
      { name: "ArrowUpDown", icon: ArrowUpDown },
      { name: "ArrowLeftRight", icon: ArrowLeftRight },
      { name: "ChevronUp", icon: ChevronUp },
      { name: "ChevronDown", icon: ChevronDown },
      { name: "ChevronLeft", icon: ChevronLeft },
      { name: "ChevronRight", icon: ChevronRight },
      { name: "ChevronsUp", icon: ChevronsUp },
      { name: "ChevronsDown", icon: ChevronsDown },
      { name: "ChevronsLeft", icon: ChevronsLeft },
      { name: "ChevronsRight", icon: ChevronsRight },
      { name: "ChevronsUpDown", icon: ChevronsUpDown },
      { name: "CornerUpRight", icon: CornerUpRight },
      { name: "CornerDownRight", icon: CornerDownRight },
      { name: "RefreshCw", icon: RefreshCw },
      { name: "RotateCw", icon: RotateCw },
      { name: "Move", icon: Move },
      { name: "MoveRight", icon: MoveRight },
      { name: "MoveLeft", icon: MoveLeft },
    ],
  },
  {
    name: "Finance & Commerce",
    icons: [
      { name: "DollarSign", icon: DollarSign },
      { name: "CircleDollarSign", icon: CircleDollarSign },
      { name: "Euro", icon: Euro },
      { name: "CreditCard", icon: CreditCard },
      { name: "Wallet", icon: Wallet },
      { name: "ShoppingCart", icon: ShoppingCart },
      { name: "ShoppingBag", icon: ShoppingBag },
      { name: "Receipt", icon: Receipt },
      { name: "Banknote", icon: Banknote },
      { name: "BadgePercent", icon: BadgePercent },
      { name: "Coins", icon: Coins },
      { name: "Store", icon: Store },
    ],
  },
  {
    name: "Access",
    icons: [
      { name: "User", icon: User },
      { name: "Users", icon: Users },
      { name: "UserCheck", icon: UserCheck },
      { name: "UserX", icon: UserX },
      { name: "UserPlus", icon: UserPlus },
      { name: "UserMinus", icon: UserMinus },
      { name: "UserCog", icon: UserCog },
      { name: "LogIn", icon: LogIn },
      { name: "LogOut", icon: LogOut },
      { name: "KeySquare", icon: KeySquare },
    ],
  },
  {
    name: "Data",
    icons: [
      { name: "Database", icon: Database },
      { name: "Server", icon: Server },
      { name: "HardDrive", icon: HardDrive },
      { name: "Cpu", icon: Cpu },
      { name: "Network", icon: Network },
      { name: "Globe", icon: Globe },
      { name: "Wifi", icon: Wifi },
      { name: "WifiOff", icon: WifiOff },
      { name: "Signal", icon: Signal },
      { name: "CloudUpload", icon: CloudUpload },
      { name: "CloudDownload", icon: CloudDownload },
      { name: "Cloud", icon: Cloud },
      { name: "FolderOpen", icon: FolderOpen },
      { name: "Folder", icon: Folder },
      { name: "FolderClosed", icon: FolderClosed },
    ],
  },
  {
    name: "Shapes",
    icons: [
      { name: "Circle", icon: Circle },
      { name: "CircleDot", icon: CircleDot },
      { name: "Square", icon: Square },
      { name: "Triangle", icon: Triangle },
      { name: "Diamond", icon: Diamond },
      { name: "Hexagon", icon: Hexagon },
      { name: "Octagon", icon: Octagon },
      { name: "Star", icon: Star },
      { name: "Minus", icon: Minus },
      { name: "Plus", icon: Plus },
      { name: "X", icon: X },
      { name: "Slash", icon: Slash },
      { name: "Dot", icon: Dot },
    ],
  },
  {
    name: "General",
    icons: [
      { name: "Home", icon: Home },
      { name: "Settings", icon: Settings },
      { name: "Settings2", icon: Settings2 },
      { name: "Bell", icon: Bell },
      { name: "BellOff", icon: BellOff },
      { name: "BellRing", icon: BellRing },
      { name: "Search", icon: Search },
      { name: "Filter", icon: Filter },
      { name: "SortAsc", icon: SortAsc },
      { name: "SortDesc", icon: SortDesc },
      { name: "MoreHorizontal", icon: MoreHorizontal },
      { name: "MoreVertical", icon: MoreVertical },
      { name: "Menu", icon: Menu },
      { name: "Hash", icon: Hash },
      { name: "Tag", icon: Tag },
      { name: "Bookmark", icon: Bookmark },
      { name: "Heart", icon: Heart },
      { name: "ThumbsUp", icon: ThumbsUp },
      { name: "ThumbsDown", icon: ThumbsDown },
      { name: "Share", icon: Share },
      { name: "Share2", icon: Share2 },
      { name: "ExternalLink", icon: ExternalLink },
      { name: "Link", icon: Link },
      { name: "Link2", icon: Link2 },
      { name: "Link2Off", icon: Link2Off },
      { name: "Copy", icon: Copy },
      { name: "Clipboard", icon: Clipboard },
      { name: "ClipboardCheck", icon: ClipboardCheck },
      { name: "ClipboardList", icon: ClipboardList },
    ],
  },
  {
    name: "Items & Feedback",
    icons: [
      { name: "CircleCheck", icon: CircleCheck },
      { name: "CircleX", icon: CircleX },
      { name: "CircleAlert", icon: CircleAlert },
      { name: "Info", icon: Info },
      { name: "CircleHelp", icon: CircleHelp },
      { name: "MessageSquare", icon: MessageSquare },
      { name: "MessageCircle", icon: MessageCircle },
      { name: "Inbox", icon: Inbox },
      { name: "Archive", icon: Archive },
      { name: "Trash", icon: Trash },
      { name: "Trash2", icon: Trash2 },
      { name: "Flag", icon: Flag },
      { name: "Zap", icon: Zap },
      { name: "ZapOff", icon: ZapOff },
      { name: "Check", icon: Check },
      { name: "Loader", icon: Loader },
      { name: "LoaderCircle", icon: LoaderCircle },
      { name: "Send", icon: Send },
      { name: "Reply", icon: Reply },
      { name: "Forward", icon: Forward },
    ],
  },
  {
    name: "Maps & Location",
    icons: [
      { name: "MapPin", icon: MapPin },
      { name: "MapPinOff", icon: MapPinOff },
      { name: "Map", icon: Map },
      { name: "Navigation", icon: Navigation },
      { name: "Navigation2", icon: Navigation2 },
      { name: "Compass", icon: Compass },
      { name: "Building", icon: Building },
      { name: "Building2", icon: Building2 },
      { name: "Hotel", icon: Hotel },
      { name: "Castle", icon: Castle },
      { name: "Mountain", icon: Mountain },
    ],
  },
  {
    name: "Users",
    icons: [
      { name: "UserRound", icon: UserRound },
      { name: "Users2", icon: Users2 },
      { name: "Contact", icon: Contact },
      { name: "Crown", icon: Crown },
      { name: "BadgeCheck", icon: BadgeCheck },
      { name: "BadgeX", icon: BadgeX },
    ],
  },
  {
    name: "Items & Services",
    icons: [
      { name: "Monitor", icon: Monitor },
      { name: "Laptop", icon: Laptop },
      { name: "Smartphone", icon: Smartphone },
      { name: "Tablet", icon: Tablet },
      { name: "Printer", icon: Printer },
      { name: "Keyboard", icon: Keyboard },
      { name: "Mouse", icon: Mouse },
      { name: "Headphones", icon: Headphones },
      { name: "Camera", icon: Camera },
      { name: "CameraOff", icon: CameraOff },
      { name: "Tv", icon: Tv },
    ],
  },
  {
    name: "Transport",
    icons: [
      { name: "Car", icon: Car },
      { name: "Truck", icon: Truck },
      { name: "Bus", icon: Bus },
      { name: "Train", icon: Train },
      { name: "Plane", icon: Plane },
      { name: "PlaneLanding", icon: PlaneLanding },
      { name: "PlaneTakeoff", icon: PlaneTakeoff },
      { name: "Ship", icon: Ship },
      { name: "Bike", icon: Bike },
      { name: "Rocket", icon: Rocket },
    ],
  },
  {
    name: "Communication",
    icons: [
      { name: "Phone", icon: Phone },
      { name: "PhoneCall", icon: PhoneCall },
      { name: "PhoneOff", icon: PhoneOff },
      { name: "PhoneIncoming", icon: PhoneIncoming },
      { name: "PhoneOutgoing", icon: PhoneOutgoing },
      { name: "Video", icon: Video },
      { name: "VideoOff", icon: VideoOff },
      { name: "Mic", icon: Mic },
      { name: "MicOff", icon: MicOff },
      { name: "Mail", icon: Mail },
      { name: "MailOpen", icon: MailOpen },
      { name: "MailCheck", icon: MailCheck },
      { name: "Radio", icon: Radio },
      { name: "Rss", icon: Rss },
    ],
  },
  {
    name: "Time",
    icons: [
      { name: "Clock", icon: Clock },
      { name: "Timer", icon: Timer },
      { name: "TimerOff", icon: TimerOff },
      { name: "AlarmClock", icon: AlarmClock },
      { name: "Calendar", icon: Calendar },
      { name: "CalendarDays", icon: CalendarDays },
      { name: "CalendarCheck", icon: CalendarCheck },
      { name: "CalendarX", icon: CalendarX },
      { name: "Hourglass", icon: Hourglass },
      { name: "Watch", icon: Watch },
    ],
  },
];
