// Design System — Tokens used by this component
// Auto-generated by scripts/export-tokens.js — do not edit by hand.
// Assumes UIColor(hex:) initializer exists in your project.

import UIKit

// MARK: - Colors

extension UIColor {
    static let severityInfo = UIColor(hex: "#7DAFD6")
    static let severityLow = UIColor(hex: "#63A100")
    static let severityMedium = UIColor(hex: "#F5BF40")
    static let severityHigh = UIColor(hex: "#D13D2E")
    static let severityCritical = UIColor(hex: "#772ED1")
    static let brandPrimary200 = UIColor(hex: "#8AC8F5")
    static let brandPrimary500 = UIColor(hex: "#1383D4")
    static let brandPrimary600 = UIColor(hex: "#0F69A9")
    static let brandSecondary200 = UIColor(hex: "#F5B6A3")
    static let brandSecondary500 = UIColor(hex: "#EE7B59")
    static let brandSecondary600 = UIColor(hex: "#E85326")
    static let scaleGreen500 = UIColor(hex: "#63A100")
    static let scaleGreen600 = UIColor(hex: "#3F6600")
    static let scaleYellow500 = UIColor(hex: "#F5BF40")
    static let scaleYellow700 = UIColor(hex: "#795706")
    static let scaleRed500 = UIColor(hex: "#D13D2E")
    static let scaleRed600 = UIColor(hex: "#8E2A1F")
    static let neutralGrey100 = UIColor(hex: "#F7F8F8")
    static let neutralGrey200 = UIColor(hex: "#F4F5F5")
    static let neutralGrey900 = UIColor(hex: "#131515")
    static let surfaceApp = UIColor(hex: "#FFFFFF")
    static let surfacePage = UIColor(hex: "#FCFDFD")
    static let surfaceRow = UIColor(hex: "#FFFFFF")
    static let surfaceRowHover = UIColor(hex: "#EBF2F7")
    static let surfaceTableHeader = UIColor(hex: "#F7F8F8")
    static let feedbackInfo = UIColor(hex: "#7DAFD6")
    static let feedbackSuccess = UIColor(hex: "#63A100")
    static let feedbackWarning = UIColor(hex: "#E6A200")
    static let feedbackAlert = UIColor(hex: "#AE2700")
    static let textPrimary = UIColor(hex: "#121F28")
    static let textSecondary = UIColor(hex: "#657078")
    static let textDisabled = UIColor(hex: "#A7ADB2")
    static let textWhite = UIColor(hex: "#FFFFFF")
}

// MARK: - Sizing (CGFloat)

extension CGFloat {
    // Spacing
    static let space2: CGFloat = 8
    static let space1: CGFloat = 4
    static let space9: CGFloat = 36
    static let space4: CGFloat = 16
    static let space3: CGFloat = 12
    static let space6: CGFloat = 24
    static let space10: CGFloat = 40
    static let space12: CGFloat = 48
    static let space5: CGFloat = 20
    static let space16: CGFloat = 64
    static let space11: CGFloat = 44
    static let space8: CGFloat = 32

    // Radius
    static let radiusMd: CGFloat = 6
    static let radiusSm: CGFloat = 2
    static let radiusFull: CGFloat = 9999
    static let radiusXl: CGFloat = 12

    // Border width
    static let borderWidth1: CGFloat = 1

    // Font size
    static let fontSize8: CGFloat = 8
    static let fontSize9: CGFloat = 9
    static let fontSize10: CGFloat = 10
    static let fontSize11: CGFloat = 11
    static let fontSize12: CGFloat = 12
    static let fontSize13: CGFloat = 13
    static let fontSize14: CGFloat = 14
    static let fontSize15: CGFloat = 15
    static let fontSize17: CGFloat = 17
    static let fontSize19: CGFloat = 19
    static let fontSize20: CGFloat = 20

    // Focus ring width
    static let ringWidth1: CGFloat = 1
    static let ringWidth2: CGFloat = 2
}

// MARK: - Font weights (use UIFont.Weight directly)
// font-weight-medium → .medium   (CSS 500)
// font-weight-semibold → .semibold   (CSS 600)
// font-weight-normal → .regular   (CSS 400)
