// Design System — Tokens used by this component
// Auto-generated by scripts/export-tokens.js — do not edit by hand.
// Assumes UIColor(hex:) initializer exists in your project.

import UIKit

// MARK: - Colors

extension UIColor {
    static let brandPrimary500 = UIColor(hex: "#1383D4")
    static let scaleRed50 = UIColor(hex: "#FCF3F2")
    static let neutralGrey100 = UIColor(hex: "#F7F8F8")
    static let surfaceApp = UIColor(hex: "#FFFFFF")
    static let textPrimary = UIColor(hex: "#121F28")
    static let textSecondary = UIColor(hex: "#657078")
    static let textDisabled = UIColor(hex: "#A7ADB2")
    static let textError = UIColor(hex: "#B0291E")
}

// MARK: - Sizing (CGFloat)

extension CGFloat {
    // Spacing
    static let space1: CGFloat = 4
    static let space3: CGFloat = 12
    static let space4: CGFloat = 16
    static let space2: CGFloat = 8
    static let space6: CGFloat = 24
    static let space5: CGFloat = 20
    static let space10: CGFloat = 40
    static let space8: CGFloat = 32

    // Radius
    static let radiusBase: CGFloat = 4
    static let radiusLg: CGFloat = 8
    static let radiusXl: CGFloat = 12

    // Border width
    static let borderWidth1: CGFloat = 1

    // Font size
    static let fontSize10: CGFloat = 10
    static let fontSize11: CGFloat = 11
    static let fontSize12: CGFloat = 12
    static let fontSize15: CGFloat = 15
}

// MARK: - Font weights (use UIFont.Weight directly)
// font-weight-semibold → .semibold   (CSS 600)
